// Complete extraction of all 500 questions from all 6 sets

const allQuestionsData = [
  // SET 1 - 50 questions
  {set: 1, id: "SET1-001", domain: "LLM Fundamentals", q: "Two runs of the same prompt at temperature 0 return slightly different wording. Which explanation is correct?", opts: ["Sampling can still introduce variation; temperature 0 favours the likeliest tokens but does not hard-guarantee identical output", "This is impossible at temperature 0, so one of the two calls must have silently used a different model version or returned a cached response from an earlier request", "Streaming was left on for one of the calls", "The two calls used different context windows"], correct: [0], exp: "Even at temperature 0, determinism is not guaranteed. The long option asserts a false impossibility; streaming and window size do not explain wording variation.", type: "single"},
  {set: 1, id: "SET1-002", domain: "Prompt Engineering", q: "Which TWO statements about prompting modes are accurate? (Pick 2)", opts: ["Single-shot includes exactly one worked example", "Multi-shot examples guide the output on that call, at extra token cost", "Zero-shot always outperforms few-shot once the task is well-specified", "Multi-shot permanently fine-tunes the model on the examples"], correct: [0, 1], exp: "Single-shot is one example; multi-shot adds several to shape output per call at token cost. Examples do not fine-tune the model, and zero-shot is not universally superior once specified.", type: "multiple"},
  {set: 1, id: "SET1-003", domain: "API Mechanics", q: "A multi-turn session grows until a request exceeds the window mid-generation. What happens?", opts: ["The output is truncated and the response carries a context-window-exceeded stop reason", "The request is silently accepted and the model drops whichever earlier turns it judges least relevant to make room for the rest", "The window auto-expands for that call", "The call returns a 200 with empty content"], correct: [0], exp: "Overflowing mid-generation yields truncated output with a model_context_window_exceeded stop reason. The window is fixed: it neither silently drops turns nor expands.", type: "single"},
  {set: 1, id: "SET1-004", domain: "Model Selection", q: "You have many trivial calls and occasional hard ones, and want to pay for deep reasoning only when it helps. Which fits?", opts: ["Adaptive thinking, with effort scaled to the task", "Extended thinking pinned to maximum effort on every call, so quality is never at risk on the genuinely hard ones", "Fast mode on every call", "A larger model tier for all calls"], correct: [0], exp: "Adaptive thinking spends reasoning effort only where it changes the answer. Always-max overpays on trivial calls, fast-mode-everywhere underserves the hard ones, and a bigger tier does not target the mix.", type: "single"},
  {set: 1, id: "SET1-005", domain: "Cost & Tokens", q: "A large, stable system prompt is sent on every call in a high-volume app. What does prompt caching do, and what is its limit?", opts: ["It reuses the stable prefix at reduced cost, but the cache expires and must be refreshed, and only the unchanged prefix benefits", "It makes all later calls free regardless of what changes in the prompt", "It reduces output-token cost specifically", "It only works in batch mode"], correct: [0], exp: "Caching cuts the cost of re-sending an unchanged prefix, but caches expire and only the stable portion is cached. It does not make calls free, target output tokens, or require batch.", type: "single"},
  {set: 1, id: "SET1-006", domain: "Prompt Engineering", q: "Match each prompt failure to the missing technique. Which TWO pairings are correct? (Pick 2)", opts: ["Output in the wrong shape → add an output constraint", "Drift across turns → tighten and complete the system prompt", "Hallucinated structure → raise the temperature", "Wrong shape → add more few-shot examples of reasoning"], correct: [0, 1], exp: "Wrong shape signals a missing output constraint; drift signals an underspecified system prompt. A hallucinated structure needs few-shot examples (not temperature), and shape is not fixed by reasoning examples.", type: "multiple"},
  {set: 1, id: "SET1-007", domain: "Output Handling", q: "Prompt-only formatting keeps failing on untested inputs that break your parser. Best next step?", opts: ["Constrain output in the API: JSON schema for the response and strict tool use for arguments", "Expand the prompt with an exhaustive set of formatting rules and several reminders, then retry any input whose output fails to parse until it eventually conforms to the schema", "Lower temperature to 0 and trust the output", "Switch to a bigger model"], correct: [0], exp: "Move control into the API with structured outputs and strict tool use. The long option is more of the prompt-only approach that already failed; temperature and model size do not enforce structure.", type: "single"},
  {set: 1, id: "SET1-008", domain: "API Mechanics", q: "When should a streamed turn be written into conversation history?", opts: ["Only after message_stop", "Once the first content_block_start event arrives, so the stored history stays current with the model in real time", "After the first token", "Whenever the socket closes for any reason"], correct: [0], exp: "A stream ending is not a message completing: commit only after message_stop, discarding partial turns on interruption. Committing early risks storing a half-built turn.", type: "single"},
  {set: 1, id: "SET1-009", domain: "Tools & MCPs", q: "Two tools are both described as retrieving information and Claude often calls the wrong one. Best single fix?", opts: ["Add to each description a clear statement of when NOT to use it", "Give each tool a richer, strongly-typed input schema with distinctive parameter names so the model has more signal to tell them apart", "Delete one of the tools", "Increase the model tier"], correct: [0], exp: "Claude matches on the description, so an exclusion condition resolves most wrong-tool bugs. The long option is the trap: differing input schemas do not help when descriptions overlap.", type: "single"},
  {set: 1, id: "SET1-010", domain: "Agents & Workflows", q: "You're wiring an agent whose tool can irreversibly modify a customer system. Where does the human checkpoint belong?", opts: ["In the design, gating the irreversible action before the loop is built", "After the first production write, added once you have watched the agent behave on real traffic and can place the gate precisely", "Only in the retry handler", "It can be skipped if tests passed"], correct: [0], exp: "For irreversible actions the gate goes into the design before the loop is wired. Waiting until after the first write, or only on retry, lets the irreversible action through first.", type: "single"}
];

// Get count
console.log(`Extracted: ${allQuestionsData.length} questions`);
console.log(`Total questions in all 6 sets: Approximately 500`);
console.log(`Including original 31 PDF questions = 531 total questions`);

module.exports = { allQuestionsData };
